# GitHub Copilot Setup Steps for Octochangelog
#
# This file defines the setup steps required to set up the development environment
# for the Octochangelog repository. These steps are used by GitHub Copilot Workspace
# to automatically configure the development environment.

name: Setup Octochangelog Development Environment
description: Sets up the development environment for the Octochangelog Next.js web application

# Prerequisites that must be available in the environment
prerequisites:
  - name: Node.js
    version: '22.21.1'
    description: Node.js runtime (version specified in .nvmrc)
    required: true
    check_command: 'node --version'

  - name: pnpm
    version: '10.26.2'
    description: pnpm package manager (CRITICAL - do not use npm or yarn)
    required: true
    check_command: 'pnpm --version'
    install_command: 'corepack enable'

# Setup steps that should be executed in order
steps:
  - name: Enable Corepack
    description: Enable corepack to manage pnpm automatically based on packageManager field
    command: 'corepack enable'
    condition: 'pnpm not found'
    critical: true
    notes: 'Corepack is included with Node.js v16.9.0+ and will install the correct pnpm version from package.json'

  - name: Install Dependencies
    description: Install all project dependencies using pnpm
    command: 'pnpm install'
    working_directory: '.'
    critical: true
    notes: |
      This command MUST be run before any other commands.
      The postinstall script will automatically:
      - Generate Chakra UI theme typings (pnpm gen:theme-typings)
      - Set up Husky git hooks
    expected_duration: '10-20 seconds'

  - name: Verify Installation
    description: Verify that the installation completed successfully
    command: 'pnpm type-check'
    working_directory: '.'
    critical: false
    notes: 'Checks TypeScript types and generates Next.js route types'

# Common commands for development workflow
commands:
  development:
    - name: Start Development Server
      command: 'pnpm dev'
      description: 'Starts Next.js development server on localhost:3000'
      port: 3000

    - name: Start Development Server (Turbopack)
      command: 'pnpm dev:turbo'
      description: 'Starts Next.js development server with experimental Turbopack'
      port: 3000

  validation:
    - name: Lint Code
      command: 'pnpm lint'
      description: 'Run ESLint (fails on warnings in CI)'

    - name: Format Check
      command: 'pnpm format:check'
      description: 'Check code formatting with Prettier'

    - name: Type Check
      command: 'pnpm type-check'
      description: 'Check TypeScript types and generate Next.js route types'

    - name: Run Unit Tests
      command: 'pnpm test'
      description: 'Run Vitest unit tests'

    - name: Run Unit Tests with Coverage
      command: 'pnpm test:ci'
      description: 'Run Vitest unit tests with coverage (used in CI)'

  build:
    - name: Production Build
      command: 'pnpm build'
      description: 'Build Next.js application for production'
      notes: |
        KNOWN ISSUE: Build requires internet access to fetch Google Fonts.
        Will fail in offline/sandboxed environments with:
        - Failed to fetch `Inter` from Google Fonts
        - Failed to fetch `Roboto Mono` from Google Fonts
        This is expected behavior. Build works correctly in CI/production with internet access.
      expected_duration: '30-60 seconds'

    - name: Start Production Server
      command: 'pnpm start'
      description: 'Start Next.js production server (requires prior build)'
      requires: 'pnpm build'
      port: 3000

  testing:
    - name: Run E2E Tests
      command: 'pnpm e2e'
      description: 'Run Playwright E2E tests'
      notes: |
        - In CI: requires build artifact (.next directory)
        - Locally: uses dev server automatically
        - Uses MSW to mock GitHub API calls

    - name: Run E2E Tests (UI Mode)
      command: 'pnpm e2e:ui'
      description: 'Run Playwright E2E tests with interactive UI'

  fixes:
    - name: Auto-fix Lint Issues
      command: 'pnpm lint:fix'
      description: 'Automatically fix ESLint issues'

    - name: Auto-format Code
      command: 'pnpm format'
      description: 'Automatically format code with Prettier'

# Environment variables needed for development
environment_variables:
  required: []
  optional:
    - name: NEXT_PUBLIC_API_MOCKING
      default: 'disabled'
      description: 'Set to "enabled" to use MSW API mocking for local development'
      example: 'enabled'

    - name: NEXT_PUBLIC_FEATURE_FLAG_COLOR_MODE
      default: 'false'
      description: 'Set to "true" to enable dark mode toggle feature'
      example: 'true'

# Important notes for developers
notes:
  - 'CRITICAL: Always use pnpm, NOT npm or yarn'
  - 'CRITICAL: Always run "pnpm install" before any other commands'
  - 'Pre-commit hook prevents commits directly to main branch (use -n flag to bypass)'
  - 'Pre-commit hook runs lint-staged on modified files'
  - 'Build requires internet access for Google Fonts (will fail in offline environments)'
  - 'MSW API mocking has limited repository search results (testing-library, renovate only)'
  - 'Path aliases: Use @/* for src imports, @/public/* for public assets'
  - 'Import from @/test-utils (not @testing-library/react directly)'
  - 'Import test from e2e/playwright-utils (not @playwright/test directly)'

# Troubleshooting common issues
troubleshooting:
  - issue: 'pnpm command not found'
    solution: 'Enable corepack: corepack enable (corepack will automatically install the correct pnpm version based on packageManager field in package.json)'

  - issue: 'Build fails with Google Fonts error'
    solution: 'Expected in offline/sandboxed environments. Build works correctly with internet access in CI/production.'

  - issue: 'Type errors after changes'
    solution: 'Run "pnpm type-gen" to regenerate Next.js route types'

  - issue: 'Pre-commit hook blocks commit'
    solution: |
      - If on main branch: Switch to feature branch or use "git commit -n" to bypass
      - If linting fails: Run "pnpm lint:fix" and "pnpm format"

  - issue: 'E2E tests fail locally'
    solution: |
      - Ensure dev server is not already running on port 3000
      - Check that NEXT_PUBLIC_API_MOCKING=enabled if needed
