# Codecov configuration
# See: https://docs.codecov.io/docs/codecov-yaml

# Make status checks informational (won't fail PRs)
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
