/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestErrorsServerSideRouteImport } from './routes/test-errors/server-side'
import { Route as TestErrorsClientSideRouteImport } from './routes/test-errors/client-side'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestErrorsServerSideRoute = TestErrorsServerSideRouteImport.update({
  id: '/test-errors/server-side',
  path: '/test-errors/server-side',
  getParentRoute: () => rootRouteImport,
} as any)
const TestErrorsClientSideRoute = TestErrorsClientSideRouteImport.update({
  id: '/test-errors/client-side',
  path: '/test-errors/client-side',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/test-errors/client-side': typeof TestErrorsClientSideRoute
  '/test-errors/server-side': typeof TestErrorsServerSideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/test-errors/client-side': typeof TestErrorsClientSideRoute
  '/test-errors/server-side': typeof TestErrorsServerSideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/test-errors/client-side': typeof TestErrorsClientSideRoute
  '/test-errors/server-side': typeof TestErrorsServerSideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/auth/callback'
    | '/test-errors/client-side'
    | '/test-errors/server-side'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/auth/callback'
    | '/test-errors/client-side'
    | '/test-errors/server-side'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/auth/callback'
    | '/test-errors/client-side'
    | '/test-errors/server-side'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  TestErrorsClientSideRoute: typeof TestErrorsClientSideRoute
  TestErrorsServerSideRoute: typeof TestErrorsServerSideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-errors/server-side': {
      id: '/test-errors/server-side'
      path: '/test-errors/server-side'
      fullPath: '/test-errors/server-side'
      preLoaderRoute: typeof TestErrorsServerSideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-errors/client-side': {
      id: '/test-errors/client-side'
      path: '/test-errors/client-side'
      fullPath: '/test-errors/client-side'
      preLoaderRoute: typeof TestErrorsClientSideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  TestErrorsClientSideRoute: TestErrorsClientSideRoute,
  TestErrorsServerSideRoute: TestErrorsServerSideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
